name: download
on:
  workflow_dispatch:

jobs:
  build:
    name: "Download on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: 4d/tool4d-action@main
      id: dlparam
      with:
        product-line: main
        version: main
        build: official
        token: ${{ secrets.DLTK }}
    - id: echodlparam
      shell: bash
      run: echo "${{ steps.dlparam.outputs.tool4d }}"

  buildtwo:
    name: "Download no opt on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: 4d/tool4d-action@main
      id: dl
    - id: echodl
      shell: bash
      run: echo "${{ steps.dl.outputs.tool4d }}"
